use wasm_bindgen_test::*;

use signal_wasm_bridge::*;

// ─── SignalProtocolAddress ───────────────────────────────────────────

#[wasm_bindgen_test]
fn address_new_valid() {
    let addr = SignalProtocolAddress::new("Alice".into(), 1).unwrap();
    assert_eq!(addr.to_string(), "Alice.1");
}

#[wasm_bindgen_test]
fn address_new_different_device_id() {
    let addr = SignalProtocolAddress::new("Bob".into(), 42).unwrap();
    assert_eq!(addr.to_string(), "Bob.42");
}

#[wasm_bindgen_test]
fn address_new_device_id_zero_should_fail() {
    // DeviceId 0 is invalid in Signal protocol
    let result = SignalProtocolAddress::new("Alice".into(), 0);
    assert!(result.is_err(), "DeviceId 0 should be rejected");
}

// ─── generate_identity_key_pair ──────────────────────────────────────

#[wasm_bindgen_test]
fn identity_key_pair_returns_valid_bytes() {
    let result = generate_identity_key_pair().unwrap();
    let bytes: Vec<u8> = serde_wasm_bindgen::from_value(result).unwrap();

    // Deserialize back into an IdentityKeyPair to prove the bytes are structurally valid
    let kp = libsignal_protocol::IdentityKeyPair::try_from(&bytes[..])
        .expect("WASM-generated bytes should deserialize into a valid IdentityKeyPair");

    // Curve25519 public key = 33 bytes (1-byte type prefix + 32-byte point)
    assert_eq!(kp.public_key().serialize().len(), 33,
        "Public key should be 33 bytes (compressed Curve25519)");

    // Curve25519 private key = 32 bytes (scalar)
    assert_eq!(kp.private_key().serialize().len(), 32,
        "Private key should be 32 bytes (Curve25519 scalar)");

    // Roundtrip: serialize again and compare to original bytes
    assert_eq!(kp.serialize().as_ref(), &bytes[..],
        "Re-serialized key pair must match original bytes exactly");
}

#[wasm_bindgen_test]
fn identity_key_pair_is_unique_each_call() {
    let a: Vec<u8> = serde_wasm_bindgen::from_value(generate_identity_key_pair().unwrap()).unwrap();
    let b: Vec<u8> = serde_wasm_bindgen::from_value(generate_identity_key_pair().unwrap()).unwrap();
    assert_ne!(a, b, "Two generated key pairs should not be identical");
}

// ─── generate_registration_id ────────────────────────────────────────

#[wasm_bindgen_test]
fn registration_id_is_14_bit() {
    // Signal spec: registration IDs are 14-bit (0..16383)
    for _ in 0..100 {
        let id = generate_registration_id().unwrap();
        assert!(id <= 0x3FFF, "Registration ID {} exceeds 14-bit max (16383)", id);
    }
}

// ─── generate_pre_keys ───────────────────────────────────────────────

#[wasm_bindgen_test]
fn pre_keys_correct_count_and_structure() {
    let result = generate_pre_keys(1, 5).unwrap();
    let arr = js_sys::Array::from(&result);
    assert_eq!(arr.length(), 5, "Should generate exactly 5 pre-keys");

    // Check first key has the expected fields
    let first = arr.get(0);
    let id = js_sys::Reflect::get(&first, &"id".into()).unwrap();
    let record = js_sys::Reflect::get(&first, &"record".into()).unwrap();
    let public_key = js_sys::Reflect::get(&first, &"publicKey".into()).unwrap();

    assert_eq!(id.as_f64().unwrap() as u32, 1, "First key should have id=1");
    assert!(!record.is_undefined(), "record field should exist");
    assert!(!public_key.is_undefined(), "publicKey field should exist");
}

#[wasm_bindgen_test]
fn pre_keys_sequential_ids() {
    let result = generate_pre_keys(100, 3).unwrap();
    let arr = js_sys::Array::from(&result);

    for i in 0..3u32 {
        let entry = arr.get(i);
        let id = js_sys::Reflect::get(&entry, &"id".into())
            .unwrap()
            .as_f64()
            .unwrap() as u32;
        assert_eq!(id, 100 + i, "Pre-key ID should be sequential from start_id");
    }
}

// ─── generate_signed_pre_key ─────────────────────────────────────────

#[wasm_bindgen_test]
fn signed_pre_key_valid_structure() {
    // First generate an identity key pair to sign with
    let ikp_bytes: Vec<u8> = serde_wasm_bindgen::from_value(
        generate_identity_key_pair().unwrap()
    ).unwrap();

    let result = generate_signed_pre_key(&ikp_bytes, 1).unwrap();

    let id = js_sys::Reflect::get(&result, &"id".into()).unwrap();
    let record = js_sys::Reflect::get(&result, &"record".into()).unwrap();
    let public_key = js_sys::Reflect::get(&result, &"publicKey".into()).unwrap();
    let signature = js_sys::Reflect::get(&result, &"signature".into()).unwrap();

    assert_eq!(id.as_f64().unwrap() as u32, 1);
    assert!(!record.is_undefined(), "record field should exist");
    assert!(!public_key.is_undefined(), "publicKey field should exist");
    assert!(!signature.is_undefined(), "signature field should exist");

    // Signature should be 64 bytes (Ed25519)
    let sig_bytes: Vec<u8> = serde_wasm_bindgen::from_value(signature).unwrap();
    assert_eq!(sig_bytes.len(), 64, "Ed25519 signature should be 64 bytes");
}

#[wasm_bindgen_test]
fn signed_pre_key_rejects_invalid_identity() {
    let bad_bytes = vec![0u8; 10]; // Too short to be a valid identity key pair
    let result = generate_signed_pre_key(&bad_bytes, 1);
    assert!(result.is_err(), "Should reject invalid identity key pair bytes");
}

// ─── generate_kyber_pre_key ──────────────────────────────────────────

#[wasm_bindgen_test]
fn kyber_pre_key_valid_structure() {
    let ikp_bytes: Vec<u8> = serde_wasm_bindgen::from_value(
        generate_identity_key_pair().unwrap()
    ).unwrap();

    let result = generate_kyber_pre_key(&ikp_bytes, 1).unwrap();

    let id = js_sys::Reflect::get(&result, &"id".into()).unwrap();
    let record = js_sys::Reflect::get(&result, &"record".into()).unwrap();
    let public_key = js_sys::Reflect::get(&result, &"publicKey".into()).unwrap();
    let signature = js_sys::Reflect::get(&result, &"signature".into()).unwrap();

    assert_eq!(id.as_f64().unwrap() as u32, 1);
    assert!(!record.is_undefined(), "record field should exist");
    assert!(!public_key.is_undefined(), "publicKey field should exist");
    assert!(!signature.is_undefined(), "signature field should exist");

    // Kyber1024 public key is much larger than Curve25519
    let pk_bytes: Vec<u8> = serde_wasm_bindgen::from_value(public_key).unwrap();
    assert!(pk_bytes.len() > 100, "Kyber public key should be significantly larger than EC keys (got {} bytes)", pk_bytes.len());
}

#[wasm_bindgen_test]
fn kyber_pre_key_rejects_invalid_identity() {
    let bad_bytes = vec![0u8; 10];
    let result = generate_kyber_pre_key(&bad_bytes, 1);
    assert!(result.is_err(), "Should reject invalid identity key pair bytes");
}
